package com.aihuishou.service.inventory.model;


import java.io.Serializable;
import java.util.Date;

public class Inventory implements Serializable {

    private Long inventoryId;

    Integer inventoryStatus;

    private String inventorySerialNumber;

    private Integer inventoryProductId;

    private Integer inventoryModelId;

    private String inventoryProductName;

    private String inventoryPricePropertyUnit;

    private String inventoryExtensionPropertyUnit;

    private Integer inventoryPrice;

    private Integer inventoryShelfId;

    private Integer inventoryOnHandQuantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.inventory_available_quantity
     *
     * @mbggenerated Thu Apr 24 18:49:14 CST 2014
     */
    private Integer inventoryAvailableQuantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.inventory_operator_id
     *
     * @mbggenerated Thu Apr 24 18:49:14 CST 2014
     */
    private Integer inventoryOperatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.inventory_operation_datetime
     *
     * @mbggenerated Thu Apr 24 18:49:14 CST 2014
     */
    private Date inventoryOperationDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.inventory_flags
     *
     * @mbggenerated Thu Apr 24 18:49:14 CST 2014
     */
    private Integer inventoryFlags;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.inventory_enter_id
     *
     * @mbggenerated Thu Apr 24 18:49:14 CST 2014
     */
    private Integer inventoryEnterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.inventory_enter_datetime
     *
     * @mbggenerated Thu Apr 24 18:49:14 CST 2014
     */
    private Date inventoryEnterDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.inventory_outer_id
     *
     * @mbggenerated Thu Apr 24 18:49:14 CST 2014
     */
    private Integer inventoryOuterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.inventory_outer_datetime
     *
     * @mbggenerated Thu Apr 24 18:49:14 CST 2014
     */
    private Date inventoryOuterDatetime;

    
    private Integer inventoryWarehouseId;
    
    private InventoryExtension inventoryExtension;
    
    private Integer inventorySkuId;
    
    private Integer inventoryLevelId;
    
    private String inventorySkuName;
    
    private String inventoryLevelName;
    
    private String inventoryShelfCode;
    
    private String inventoryImei;

    private static final long serialVersionUID = 1L;

    public Long getInventoryId() {
        return inventoryId;
    }

    public void setInventoryId(Long inventoryId) {
        this.inventoryId = inventoryId;
    }

    public Integer getInventoryStatus() {
        return inventoryStatus;
    }

    public void setInventoryStatus(Integer inventoryStatus) {
        this.inventoryStatus = inventoryStatus;
    }

    public String getInventorySerialNumber() {
        return inventorySerialNumber;
    }

    public void setInventorySerialNumber(String inventorySerialNumber) {
        this.inventorySerialNumber = inventorySerialNumber;
    }

    public Integer getInventoryProductId() {
        return inventoryProductId;
    }

    public void setInventoryProductId(Integer inventoryProductId) {
        this.inventoryProductId = inventoryProductId;
    }

    public Integer getInventoryModelId() {
        return inventoryModelId;
    }

    public void setInventoryModelId(Integer inventoryModelId) {
        this.inventoryModelId = inventoryModelId;
    }

    public String getInventoryPricePropertyUnit() {
        return inventoryPricePropertyUnit;
    }

    public void setInventoryPricePropertyUnit(String inventoryPricePropertyUnit) {
        this.inventoryPricePropertyUnit = inventoryPricePropertyUnit;
    }

    public String getInventoryExtensionPropertyUnit() {
        return inventoryExtensionPropertyUnit;
    }

    public void setInventoryExtensionPropertyUnit(String inventoryExtensionPropertyUnit) {
        this.inventoryExtensionPropertyUnit = inventoryExtensionPropertyUnit;
    }

    public Integer getInventoryPrice() {
        return inventoryPrice;
    }

    public void setInventoryPrice(Integer inventoryPrice) {
        this.inventoryPrice = inventoryPrice;
    }

    public Integer getInventoryShelfId() {
        return inventoryShelfId;
    }

    public void setInventoryShelfId(Integer inventoryShelfId) {
        this.inventoryShelfId = inventoryShelfId;
    }

    public Integer getInventoryOnHandQuantity() {
        return inventoryOnHandQuantity;
    }

    public void setInventoryOnHandQuantity(Integer inventoryOnHandQuantity) {
        this.inventoryOnHandQuantity = inventoryOnHandQuantity;
    }

    public Integer getInventoryAvailableQuantity() {
        return inventoryAvailableQuantity;
    }

    public void setInventoryAvailableQuantity(Integer inventoryAvailableQuantity) {
        this.inventoryAvailableQuantity = inventoryAvailableQuantity;
    }

    public Integer getInventoryOperatorId() {
        return inventoryOperatorId;
    }

    public void setInventoryOperatorId(Integer inventoryOperatorId) {
        this.inventoryOperatorId = inventoryOperatorId;
    }

    public Date getInventoryOperationDatetime() {
        return inventoryOperationDatetime;
    }

    public void setInventoryOperationDatetime(Date inventoryOperationDatetime) {
        this.inventoryOperationDatetime = inventoryOperationDatetime;
    }

    public Integer getInventoryFlags() {
        return inventoryFlags;
    }

    public void setInventoryFlags(Integer inventoryFlags) {
        this.inventoryFlags = inventoryFlags;
    }

    public Integer getInventoryEnterId() {
        return inventoryEnterId;
    }

    public void setInventoryEnterId(Integer inventoryEnterId) {
        this.inventoryEnterId = inventoryEnterId;
    }

    public Date getInventoryEnterDatetime() {
        return inventoryEnterDatetime;
    }

    public void setInventoryEnterDatetime(Date inventoryEnterDatetime) {
        this.inventoryEnterDatetime = inventoryEnterDatetime;
    }

    public Integer getInventoryOuterId() {
        return inventoryOuterId;
    }

    public void setInventoryOuterId(Integer inventoryOuterId) {
        this.inventoryOuterId = inventoryOuterId;
    }

    public Date getInventoryOuterDatetime() {
        return inventoryOuterDatetime;
    }

    public void setInventoryOuterDatetime(Date inventoryOuterDatetime) {
        this.inventoryOuterDatetime = inventoryOuterDatetime;
    }

	public InventoryExtension getInventoryExtension() {
		return inventoryExtension;
	}

	public void setInventoryExtension(InventoryExtension inventoryExtension) {
		this.inventoryExtension = inventoryExtension;
	}

	public String getInventoryProductName() {
		return inventoryProductName;
	}

	public void setInventoryProductName(String inventoryProductName) {
		this.inventoryProductName = inventoryProductName;
	}

	public Integer getInventoryWarehouseId() {
		return inventoryWarehouseId;
	}

	public void setInventoryWarehouseId(Integer inventoryWarehouseId) {
		this.inventoryWarehouseId = inventoryWarehouseId;
	}

	public Integer getInventorySkuId() {
		return inventorySkuId;
	}

	public void setInventorySkuId(Integer inventorySkuId) {
		this.inventorySkuId = inventorySkuId;
	}

	public Integer getInventoryLevelId() {
		return inventoryLevelId;
	}

	public void setInventoryLevelId(Integer inventoryLevelId) {
		this.inventoryLevelId = inventoryLevelId;
	}

	public String getInventorySkuName() {
		return inventorySkuName;
	}

	public void setInventorySkuName(String inventorySkuName) {
		this.inventorySkuName = inventorySkuName;
	}

	public String getInventoryLevelName() {
		return inventoryLevelName;
	}

	public void setInventoryLevelName(String inventoryLevelName) {
		this.inventoryLevelName = inventoryLevelName;
	}

	public String getInventoryShelfCode() {
		return inventoryShelfCode;
	}

	public void setInventoryShelfCode(String inventoryShelfCode) {
		this.inventoryShelfCode = inventoryShelfCode;
	}

	public String getInventorySpuId() {
		if(inventorySkuId==null){
			return null;
		}
		
		if(inventoryLevelId==null){
			return null;
		}
		
		return SaleSkuQuanlity.getSPU(inventorySkuId, inventoryLevelId);
	}

	public String getInventoryImei() {
		return inventoryImei;
	}

	public void setInventoryImei(String inventoryImei) {
		this.inventoryImei = inventoryImei;
	}

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Inventory inventory = (Inventory) o;

        if (inventoryId != null ? !inventoryId.equals(inventory.inventoryId) : inventory.inventoryId != null)
            return false;
        if (inventoryStatus != null ? !inventoryStatus.equals(inventory.inventoryStatus) : inventory.inventoryStatus != null)
            return false;
        if (inventorySerialNumber != null ? !inventorySerialNumber.equals(inventory.inventorySerialNumber) : inventory.inventorySerialNumber != null)
            return false;
        if (inventoryProductId != null ? !inventoryProductId.equals(inventory.inventoryProductId) : inventory.inventoryProductId != null)
            return false;
        if (inventoryModelId != null ? !inventoryModelId.equals(inventory.inventoryModelId) : inventory.inventoryModelId != null)
            return false;
        if (inventoryProductName != null ? !inventoryProductName.equals(inventory.inventoryProductName) : inventory.inventoryProductName != null)
            return false;
        if (inventoryPricePropertyUnit != null ? !inventoryPricePropertyUnit.equals(inventory.inventoryPricePropertyUnit) : inventory.inventoryPricePropertyUnit != null)
            return false;
        if (inventoryExtensionPropertyUnit != null ? !inventoryExtensionPropertyUnit.equals(inventory.inventoryExtensionPropertyUnit) : inventory.inventoryExtensionPropertyUnit != null)
            return false;
        if (inventoryPrice != null ? !inventoryPrice.equals(inventory.inventoryPrice) : inventory.inventoryPrice != null)
            return false;
        if (inventoryShelfId != null ? !inventoryShelfId.equals(inventory.inventoryShelfId) : inventory.inventoryShelfId != null)
            return false;
        if (inventoryOnHandQuantity != null ? !inventoryOnHandQuantity.equals(inventory.inventoryOnHandQuantity) : inventory.inventoryOnHandQuantity != null)
            return false;
        if (inventoryAvailableQuantity != null ? !inventoryAvailableQuantity.equals(inventory.inventoryAvailableQuantity) : inventory.inventoryAvailableQuantity != null)
            return false;
        if (inventoryOperatorId != null ? !inventoryOperatorId.equals(inventory.inventoryOperatorId) : inventory.inventoryOperatorId != null)
            return false;
        if (inventoryOperationDatetime != null ? !inventoryOperationDatetime.equals(inventory.inventoryOperationDatetime) : inventory.inventoryOperationDatetime != null)
            return false;
        if (inventoryFlags != null ? !inventoryFlags.equals(inventory.inventoryFlags) : inventory.inventoryFlags != null)
            return false;
        if (inventoryEnterId != null ? !inventoryEnterId.equals(inventory.inventoryEnterId) : inventory.inventoryEnterId != null)
            return false;
        if (inventoryEnterDatetime != null ? !inventoryEnterDatetime.equals(inventory.inventoryEnterDatetime) : inventory.inventoryEnterDatetime != null)
            return false;
        if (inventoryOuterId != null ? !inventoryOuterId.equals(inventory.inventoryOuterId) : inventory.inventoryOuterId != null)
            return false;
        if (inventoryOuterDatetime != null ? !inventoryOuterDatetime.equals(inventory.inventoryOuterDatetime) : inventory.inventoryOuterDatetime != null)
            return false;
        if (inventoryWarehouseId != null ? !inventoryWarehouseId.equals(inventory.inventoryWarehouseId) : inventory.inventoryWarehouseId != null)
            return false;
        if (inventoryExtension != null ? !inventoryExtension.equals(inventory.inventoryExtension) : inventory.inventoryExtension != null)
            return false;
        if (inventorySkuId != null ? !inventorySkuId.equals(inventory.inventorySkuId) : inventory.inventorySkuId != null)
            return false;
        if (inventoryLevelId != null ? !inventoryLevelId.equals(inventory.inventoryLevelId) : inventory.inventoryLevelId != null)
            return false;
        if (inventorySkuName != null ? !inventorySkuName.equals(inventory.inventorySkuName) : inventory.inventorySkuName != null)
            return false;
        if (inventoryLevelName != null ? !inventoryLevelName.equals(inventory.inventoryLevelName) : inventory.inventoryLevelName != null)
            return false;
        if (inventoryShelfCode != null ? !inventoryShelfCode.equals(inventory.inventoryShelfCode) : inventory.inventoryShelfCode != null)
            return false;
        return inventoryImei != null ? inventoryImei.equals(inventory.inventoryImei) : inventory.inventoryImei == null;

    }

    @Override
    public int hashCode() {
        int result = inventoryId != null ? inventoryId.hashCode() : 0;
        result = 31 * result + (inventoryStatus != null ? inventoryStatus.hashCode() : 0);
        result = 31 * result + (inventorySerialNumber != null ? inventorySerialNumber.hashCode() : 0);
        result = 31 * result + (inventoryProductId != null ? inventoryProductId.hashCode() : 0);
        result = 31 * result + (inventoryModelId != null ? inventoryModelId.hashCode() : 0);
        result = 31 * result + (inventoryProductName != null ? inventoryProductName.hashCode() : 0);
        result = 31 * result + (inventoryPricePropertyUnit != null ? inventoryPricePropertyUnit.hashCode() : 0);
        result = 31 * result + (inventoryExtensionPropertyUnit != null ? inventoryExtensionPropertyUnit.hashCode() : 0);
        result = 31 * result + (inventoryPrice != null ? inventoryPrice.hashCode() : 0);
        result = 31 * result + (inventoryShelfId != null ? inventoryShelfId.hashCode() : 0);
        result = 31 * result + (inventoryOnHandQuantity != null ? inventoryOnHandQuantity.hashCode() : 0);
        result = 31 * result + (inventoryAvailableQuantity != null ? inventoryAvailableQuantity.hashCode() : 0);
        result = 31 * result + (inventoryOperatorId != null ? inventoryOperatorId.hashCode() : 0);
        result = 31 * result + (inventoryOperationDatetime != null ? inventoryOperationDatetime.hashCode() : 0);
        result = 31 * result + (inventoryFlags != null ? inventoryFlags.hashCode() : 0);
        result = 31 * result + (inventoryEnterId != null ? inventoryEnterId.hashCode() : 0);
        result = 31 * result + (inventoryEnterDatetime != null ? inventoryEnterDatetime.hashCode() : 0);
        result = 31 * result + (inventoryOuterId != null ? inventoryOuterId.hashCode() : 0);
        result = 31 * result + (inventoryOuterDatetime != null ? inventoryOuterDatetime.hashCode() : 0);
        result = 31 * result + (inventoryWarehouseId != null ? inventoryWarehouseId.hashCode() : 0);
        result = 31 * result + (inventoryExtension != null ? inventoryExtension.hashCode() : 0);
        result = 31 * result + (inventorySkuId != null ? inventorySkuId.hashCode() : 0);
        result = 31 * result + (inventoryLevelId != null ? inventoryLevelId.hashCode() : 0);
        result = 31 * result + (inventorySkuName != null ? inventorySkuName.hashCode() : 0);
        result = 31 * result + (inventoryLevelName != null ? inventoryLevelName.hashCode() : 0);
        result = 31 * result + (inventoryShelfCode != null ? inventoryShelfCode.hashCode() : 0);
        result = 31 * result + (inventoryImei != null ? inventoryImei.hashCode() : 0);
        return result;
    }

    @Override
    public String toString() {
        return "Inventory{" +
                "inventoryId=" + inventoryId +
                ", inventoryStatus=" + inventoryStatus +
                ", inventorySerialNumber='" + inventorySerialNumber + '\'' +
                ", inventoryProductId=" + inventoryProductId +
                ", inventoryModelId=" + inventoryModelId +
                ", inventoryProductName='" + inventoryProductName + '\'' +
                ", inventoryPricePropertyUnit='" + inventoryPricePropertyUnit + '\'' +
                ", inventoryExtensionPropertyUnit='" + inventoryExtensionPropertyUnit + '\'' +
                ", inventoryPrice=" + inventoryPrice +
                ", inventoryShelfId=" + inventoryShelfId +
                ", inventoryOnHandQuantity=" + inventoryOnHandQuantity +
                ", inventoryAvailableQuantity=" + inventoryAvailableQuantity +
                ", inventoryOperatorId=" + inventoryOperatorId +
                ", inventoryOperationDatetime=" + inventoryOperationDatetime +
                ", inventoryFlags=" + inventoryFlags +
                ", inventoryEnterId=" + inventoryEnterId +
                ", inventoryEnterDatetime=" + inventoryEnterDatetime +
                ", inventoryOuterId=" + inventoryOuterId +
                ", inventoryOuterDatetime=" + inventoryOuterDatetime +
                ", inventoryWarehouseId=" + inventoryWarehouseId +
                ", inventoryExtension=" + inventoryExtension +
                ", inventorySkuId=" + inventorySkuId +
                ", inventoryLevelId=" + inventoryLevelId +
                ", inventorySkuName='" + inventorySkuName + '\'' +
                ", inventoryLevelName='" + inventoryLevelName + '\'' +
                ", inventoryShelfCode='" + inventoryShelfCode + '\'' +
                ", inventoryImei='" + inventoryImei + '\'' +
                '}';
    }
}